version: '3.8'

services:
  db:
    container_name: db
    build: ./db-init/
    # image: postgres:latest
    # environment:
    #   POSTGRES_DB: iris
    #   POSTGRES_USER: alex
    #   POSTGRES_PASSWORD: notsure
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: app
    build: ./flask-app/
    environment:
      - DB_HOST=db
      - DB_NAME=iris
      - DB_USER=alex
      - DB_PASSWORD=notsure
    depends_on:
      - db
    ports:
      - "5001:5001"

volumes:
  db-data:
