version: '3.8'

services:
  db:
    container_name: db
    build: ./db-init/
    ports:
      - "5432:5432"
  
  db-init:
    container_name: db-init
    build: ./organisateur/
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=iris
      - DB_USER=alex
      - DB_PASSWORD=notsure

  app:
    container_name: app
    build: ./flask-app/
    environment:
      - DB_HOST=db
      - DB_NAME=iris
      - DB_USER=alex
      - DB_PASSWORD=notsure
    depends_on:
      - db
    ports:
      - "5001:5001"

volumes:
  db-data:
