FROM postgres:latest

RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install psycopg2-binary

COPY requirements.txt .
RUN pip install -r requirements.txt

ENV POSTGRES_DB=iris
ENV POSTGRES_USER=alex
ENV POSTGRES_PASSWORD=notsure

COPY init.sql /docker-entrypoint-initdb.d/
COPY init.py /docker-entrypoint-initdb.d/

EXPOSE 5432

CMD ["python3", "/docker-entrypoint-initdb.d/init.py"]


# real good usage
# FROM postgres:latest
# ENV POSTGRES_DB=iris
# ENV POSTGRES_USER=alex
# ENV POSTGRES_PASSWORD=notsure
# COPY init.sql /docker-entrypoint-initdb.d/
# EXPOSE 5432